version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mindmate_backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mindmate_frontend
    ports:
      - "8501:8501"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - backend

  db:
    image: ankane/pgvector
    container_name: mindmate_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mindmate_pgadmin
    ports:
      - "8080:80"
    env_file: .env
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
