
from openai import AsyncOpenAI

#load_dotenv()
from dotenv import load_dotenv
load_dotenv()

client = AsyncOpenAI()

from openai import AsyncOpenAI

client = AsyncOpenAI()


async def generate_prompt(user_input: str) -> str:
    """
    Generates a reflective journaling question based on user input.

    Parameters:
        user_input (str): The user's message or journal request.

    Returns:
        str: A reflective question generated by the journaling coach.
    """
    system_prompt = (
        "You are a thoughtful journaling coach. "
        "Given any user input, respond with a single reflective question "
        "that helps the user explore their thoughts or emotions."
    )

    response = await client.chat.completions.create(
        model="gpt-4.1-nano",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_input}
        ]
    )

    return response.choices[0].message.content.strip()

